name: Validate

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    name: Home Assistant hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@master
